### ISSUE TITLE
Amend "Ripple sells to banks"

### ISSUE THREAD

**Issue by SASchofield** [WietseWind/xrp-fud-bingo#11]
Issue - Accuracy of information:
It is important to offer up to date information so XRP buyers can make informed purchases. I note this one page hasn't been updated & think it would be beneficial to do so.

Fix - Amend page [https://fudbingo.com/ripple-sells-to-banks-exchanges-at-a-discount](Ripple sells to banks) to acknowledge XRP sales, at discount, to financial institutions like investment funds.

Suggestion:

- "Bradley Garlinghouse; CEO of Ripple Inc; has acknowledged discounted sales to institutional investors with restrictions in place. Restrictions used to ensure those buyers' were unable to 'dump' into the market after they purchased. He said this during an interview, September 2019, with Julia Chatterley of CNN."
- "These buyers were typically funds, with intentions to hold XRP long-term. Purportedly the largest discounts may have been up to 30% off market price during time of sale. Usually restrictions included lock-ups or instructions on sale percentages allowable, based on daily trading volume."

Expand: 

- "Mr Garlinghouse made it clear during this interview that banks & other partners using On-Demand Liquidity (formerly "xRapid") purchased & sold XRP on the open-market at market price. Which is how ODL is intended to function. He did not comment on exchanges making purchases, the question had not been asked." 
- "Financial institutions may wish to buy/sell assets due to legal obligations, or to balance investment portfolios."

**Comment by Wietse-Livingroom** [comment]
Thank you, that's a great suggestion. 
I updated it from Debunked to Nuanced, with your text:
![image](https://user-images.githubusercontent.com/65833392/103457631-3a19af80-4d01-11eb-9219-89a2575b9a90.png)
![image](https://user-images.githubusercontent.com/65833392/103457643-3f76fa00-4d01-11eb-9a39-3f7be9083871.png)
